In [1]:
import math

In [2]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module is always available.  It provides access to the
    mathematical functions defined by the C standard.

FUNCTIONS
    acos(...)
        acos(x)
        
        Return the arc cosine (measured in radians) of x.
    
    acosh(...)
        acosh(x)
        
        Return the inverse hyperbolic cosine of x.
    
    asin(...)
        asin(x)
        
        Return the arc sine (measured in radians) of x.
    
    asinh(...)
        asinh(x)
        
        Return the inverse hyperbolic sine of x.
    
    atan(...)
        atan(x)
        
        Return the arc tangent (measured in radians) of x.
    
    atan2(...)
        atan2(y, x)
        
        Return the arc tangent (measured in radians) of y/x.
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(...)
        atanh(x)
        
        Return the inverse hyperbolic tangent of x.
    
    ceil(...)
        ceil(x)
        
 

In [3]:
help(math.sqrt)

Help on built-in function sqrt in module math:

sqrt(...)
    sqrt(x)
    
    Return the square root of x.



In [4]:
type(math)

module

In [5]:
type(math.sqrt)

builtin_function_or_method

In [6]:
type(math.sqrt(10))

float

In [7]:
math.sqrt(10)

3.1622776601683795

In [8]:
for i in range(1,10): print(i,'   ',math.sqrt(i))

1     1.0
2     1.4142135623730951
3     1.7320508075688772
4     2.0
5     2.23606797749979
6     2.449489742783178
7     2.6457513110645907
8     2.8284271247461903
9     3.0


In [9]:
for i in range(3,30,3): print(i,'   ',math.sqrt(i))

3     1.7320508075688772
6     2.449489742783178
9     3.0
12     3.4641016151377544
15     3.872983346207417
18     4.242640687119285
21     4.58257569495584
24     4.898979485566356
27     5.196152422706632


In [10]:
for i in range(3,30,3): print('{:2}'.format(i),'   ',math.sqrt(i))

 3     1.7320508075688772
 6     2.449489742783178
 9     3.0
12     3.4641016151377544
15     3.872983346207417
18     4.242640687119285
21     4.58257569495584
24     4.898979485566356
27     5.196152422706632


In [11]:
for i in range(3,30):
    if math.sqrt(i)==math.floor(math.sqrt(i)):
        print(i,'   ',math.sqrt(i))

4     2.0
9     3.0
16     4.0
25     5.0


In [12]:
for i in range(3,30):
    if math.sqrt(i)==int(math.sqrt(i)):
        print('{:2}'.format(i), '   ',math.sqrt(i))

 4     2.0
 9     3.0
16     4.0
25     5.0


In [13]:
for i in range(3,30):
    if math.sqrt(i)!=int(math.sqrt(i)):
        print('{:2}'.format(i), '   ',math.sqrt(i))

 3     1.7320508075688772
 5     2.23606797749979
 6     2.449489742783178
 7     2.6457513110645907
 8     2.8284271247461903
10     3.1622776601683795
11     3.3166247903554
12     3.4641016151377544
13     3.605551275463989
14     3.7416573867739413
15     3.872983346207417
17     4.123105625617661
18     4.242640687119285
19     4.358898943540674
20     4.47213595499958
21     4.58257569495584
22     4.69041575982343
23     4.795831523312719
24     4.898979485566356
26     5.0990195135927845
27     5.196152422706632
28     5.291502622129181
29     5.385164807134504


In [14]:
1/7

0.14285714285714285

In [15]:
for i in range(1,8): print(i,'   ',i/7)

1     0.14285714285714285
2     0.2857142857142857
3     0.42857142857142855
4     0.5714285714285714
5     0.7142857142857143
6     0.8571428571428571
7     1.0


For the cell below, set the variable 'n' to 5, 6, 7, 8 and 9 and see how the results change.

In [16]:
n=5
for i in range(1,n+1): print(i,'   ',i/n)

1     0.2
2     0.4
3     0.6
4     0.8
5     1.0


In [17]:
from sympy import Symbol, solve

In [18]:
x=Symbol('x')

In [19]:
expr=x-5-7

In [20]:
solve(expr)

[12]

In [21]:
quadratic=x**2+5*x+4

In [22]:
solve(quadratic)

[-4, -1]

In [25]:
x=Symbol('x')
y=Symbol('y')
expr1=x+y-5
expr2=x*y-6

In [26]:
solve((expr1,expr2),dict=True)

[{x: 2, y: 3}, {x: 3, y: 2}]

In [27]:
import numpy as np

In [28]:
sqrts = np.sqrt([6, 10, 18])

In [29]:
sqrts

array([2.44948974, 3.16227766, 4.24264069])

In [30]:
demo_matrix=np.matrix([[1,2],[3,4]])

In [31]:
np.sqrt(demo_matrix)

matrix([[1.        , 1.41421356],
        [1.73205081, 2.        ]])

In [32]:
b = np.arange(9).reshape(3,3)

In [33]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
np.sqrt(b)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [35]:
np.format_float_positional(np.float16(0.3), unique=False, precision=10)

'0.3000488281'

In [36]:
np.float128(np.pi)

3.141592653589793116

In [37]:
pi=np.pi

In [38]:
??pi

Type:        float
String form: 3.141592653589793
Docstring:  
float(x) -> floating point number

Convert a string or number to a floating point number, if possible.


In [39]:
np.float128(1)/7

0.14285714285714285714

In [40]:
80/math.log(10,2)

24.082399653118493

In [41]:
np

<module 'numpy' from '/home/AlbertKang/.local/lib/python3.6/site-packages/numpy/__init__.py'>

In [42]:
np.format_float_positional(np.arange(8), unique=True, precision=60)

TypeError: only size-1 arrays can be converted to Python scalars

In [43]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_distributor_init',
 '_global

In [44]:
np.version()

TypeError: 'module' object is not callable

In [45]:
np.sqrt(3)

1.7320508075688772

In [46]:
3**0.5

1.7320508075688772

In [47]:
np.sqrt(np.arange(8))

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131])

In [48]:
(np.arange(8))**0.5

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131])

In [49]:
npsquares=(np.arange(8))**2

In [64]:
npexps=2**np.arange(8)

In [65]:
type(np.arange(8))

numpy.ndarray

In [66]:
rpow_method = np.arange(8).__rpow__

In [67]:
?? rpow_method

Signature:       rpow_method(value, mod=None, /)
Call signature:  rpow_method(*args, **kwargs)
Type:           method-wrapper
String form:    <method-wrapper '__rpow__' of numpy.ndarray object at 0x7fb01a308e40>
Docstring:      Return pow(value, self, mod).


In [68]:
npexps

array([  1,   2,   4,   8,  16,  32,  64, 128])

In [69]:
type(npexps)

numpy.ndarray

In [70]:
npsquares

array([ 0,  1,  4,  9, 16, 25, 36, 49])

In [71]:
npcounter=np.arange(8)

In [72]:
npcounter

array([0, 1, 2, 3, 4, 5, 6, 7])

In [73]:
import pandas as pd

In [74]:
df1 = pd.DataFrame({'x**2':npsquares,'2**x':npexps})

In [75]:
df1

x**2  2**x
0     0     1
1     1     2
2     4     4
3     9     8
4    16    16
5    25    32
6    36    64
7    49   128

In [77]:
for i in range(0,8): print(math.factorial(i))

1
1
2
6
24
120
720
5040


In [78]:
factorials=[math.factorial(i) for i in range(0,8)]
#xx=[(i) for i in (dir(math)) if not i.startswith('_')]

In [79]:
factorials

[1, 1, 2, 6, 24, 120, 720, 5040]

In [80]:
type(factorials)

list

In [81]:
factorials=np.array(factorials)

In [82]:
type(factorials)

numpy.ndarray

In [83]:
df1 = pd.DataFrame({'x**2':npsquares,'2**x':npexps, 'x!':factorials})

In [84]:
df1

x**2  2**x    x!
0     0     1     1
1     1     2     1
2     4     4     2
3     9     8     6
4    16    16    24
5    25    32   120
6    36    64   720
7    49   128  5040

In [85]:
df1.columns

Index(['x**2', '2**x', 'x!'], dtype='object')

In [86]:
for index, row in df1.iterrows():
    print(row.to_frame().T)

   x**2  2**x  x!
0     0     1   1
   x**2  2**x  x!
1     1     2   1
   x**2  2**x  x!
2     4     4   2
   x**2  2**x  x!
3     9     8   6
   x**2  2**x  x!
4    16    16  24
   x**2  2**x   x!
5    25    32  120
   x**2  2**x   x!
6    36    64  720
   x**2  2**x    x!
7    49   128  5040


In [87]:
df1.T  

0  1  2  3   4    5    6     7
x**2  0  1  4  9  16   25   36    49
2**x  1  2  4  8  16   32   64   128
x!    1  1  2  6  24  120  720  5040

In [103]:
def sieve(limit):
    numbers = set(range(1,limit+1))
    for n in range(2,int(math.sqrt(limit))+1):
        m=2
        while (n*m <= limit):
            numbers.discard(n*m)
            m+=1
    print(numbers)

In [111]:
def sieve_list(limit):
    numbers = list(range(1,limit+1))
    for n in range(2,int(math.sqrt(limit))+1):
        m=2
        while (n*m <= limit):
            if numbers.count(n*m) > 0:
                numbers.remove(n*m)
            m+=1
    print(numbers)

In [112]:
sieve_list(200)

[1, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199]


In [106]:
dir([])

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [110]:
l = []
? l.count

Docstring: L.count(value) -> integer -- return number of occurrences of value
Type:      builtin_function_or_method
