In [63]:
from datascience import *
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [64]:
rawdata=Table.read_table('/home/abcaslow/heartrate.csv')

In [65]:
rawdata.column(0)

array(['2020-10-01 20:42:22 -0400', '2020-10-01 20:47:46 -0400',
       '2020-10-01 20:50:14 -0400', ..., '2021-03-18 02:39:51 -0400',
       '2021-03-18 02:44:16 -0400', '2021-03-18 02:50:46 -0400'],
      dtype='<U25')

In [66]:
np.char.rstrip(rawdata.column(0),' -0400')
#xstrip=rawdata.column(0)
#outarray=np.char.rstrip(xstrip,'-0400')
#print(outarray)

array(['2020-10-01 20:42:22', '2020-10-01 20:47:46', '2020-10-01 20:50:1',
       ..., '2021-03-18 02:39:51', '2021-03-18 02:44:16',
       '2021-03-18 02:50:46'], dtype='<U25')

In [67]:
rawdata.labels

('timestamp', 'heartrate')

In [119]:
rawdata.column(0)

array(['2020-10-01 20:42:22 -0400', '2020-10-01 20:47:46 -0400',
       '2020-10-01 20:50:14 -0400', ..., '2021-03-18 02:39:51 -0400',
       '2021-03-18 02:44:16 -0400', '2021-03-18 02:50:46 -0400'],
      dtype='<U25')

In [68]:
#help(rawdata.where)

In [108]:
#rawdata.where('heartrate', are.above(120)).plot('timestamp')
#rawdata.where('heartrate', are.above(50))
#orange=rawdata.where('heartrate', are.between(180, 220)).take(np.arange(5,20))
orange=rawdata.where('timestamp', are.containing('11-22')).where('heartrate', are.between(10, 50))
np.mean(orange.column(1))
np.percentile(orange.column(1),50,axis=0)
#orange=rawdata.where('heartrate', are.between(10, 50))
#orange=rawdata.where('heartrate', are.between(10, 50))
#green=rawdata.where('heartrate', are.between(35, 100)).column(1).mean()
#rawdata.where('heartrate', are.equal_to(141)).plot('timestamp')

48.0

In [122]:
x=np.char.rstrip(orange.column(0),' -0400')
x=np.char.replace(x,'20', "",count=1)
x

array(['20-11-22 03:52:36', '20-11-22 04:45:32', '20-11-22 05:10:26',
       '20-11-22 05:15:41', '20-11-22 05:43:58', '20-11-22 05:45:25',
       '20-11-22 06:22:23'], dtype='<U17')

In [128]:
import functools
?functools.reduce

Docstring:
reduce(function, sequence[, initial]) -> value

Apply a function of two arguments cumulatively to the items of a sequence,
from left to right, so as to reduce the sequence to a single value.
For example, reduce(lambda x, y: x+y, [1, 2, 3, 4, 5]) calculates
((((1+2)+3)+4)+5).  If initial is present, it is placed before the items
of the sequence in the calculation, and serves as a default when the
sequence is empty.
Type:      builtin_function_or_method


In [129]:
#x=orange.column(0)
y=orange.column(1)
functools.reduce(max, y)

49.0

In [117]:
plt.plot(x,y)
plt.xticks(rotation=45)
plt.grid(True)
manager=plt.get_current_fig_manager()
manager.full_screen_toggle()
#fig=plt.figure()
#fig.canvas.manager.full_screen_toggle()
#fig.show()
#manager.window.showMaximized() # error
#manager.show()
plt.show()
orange.rows

rawdata.column(1).mean()

x=np.arange(0,6)
x**2

In [23]:
type(hb)

numpy.ndarray

In [24]:
import numpy as np

In [46]:
hb

array([ 99.,  67., 107., ...,  61.,  62.,  65.])

array([107.,  63.,  57.,  67.,  77.,  70.,  74.])

In [43]:
number_patterns=np.arange(11)
number_patterns/8

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ,
       1.125, 1.25 ])

In [82]:
hb>100

array([False, False,  True, ..., False, False, False])

In [88]:
hb[hb >50]

array([ 99.,  67., 107., ...,  61.,  62.,  65.])

In [30]:
list=[21,100,5,-10,52]

In [59]:
listvar=[i for i in range(11)]
listvar/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [60]:
arrayvar=np.arange(11)
arrayvar/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [100]:
len(np.arange(0,hb.shape[0])[hb > 90])

3781

In [28]:
mask=hb>100

In [30]:
print(mask)

[False False  True ... False False False]


In [31]:
hb[mask]=0

In [32]:
print(hb)

[99. 67.  0. ... 61. 62. 65.]


In [70]:
demo_matrix=np.matrix([[1,2],[3,4]])

I am thinking of 2 numbers. Add them together you get X. Subtract them Y.

$a+b = X$

$a-b = Y$

$\begin{bmatrix}1&1\\1&-1\end{bmatrix} \begin{bmatrix}a\\b\end{bmatrix} = \begin{bmatrix}X\\Y\end{bmatrix}$

In [71]:
demo_matrix=np.matrix([[1,1],[1,-1]])

In [72]:
demo_matrix

matrix([[ 1,  1],
        [ 1, -1]])

In [75]:
np.linalg.inv(demo_matrix)

matrix([[ 0.5,  0.5],
        [ 0.5, -0.5]])

$\begin{bmatrix}a\\b\end{bmatrix} = \begin{bmatrix}0.5&0.5\\0.5&-0.5\end{bmatrix} \begin{bmatrix}X\\Y\end{bmatrix}$

$a = 0.5X + 0.5Y$

$b = 0.5X - 0.5Y$