<b>Distance = Rate * Time</b>
Flaw in the model used in this Notebook: We are applying constant velocity only in the following Notebook.  No runner acceleration is measured.  


In [147]:
import numpy as np

In [148]:
time = np.arange(0,31)
time = np.arange(0,16,0.5)

In [149]:
time

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5])

In [150]:
runner1=a*40

In [151]:
runner1

array([  0.,  20.,  40.,  60.,  80., 100., 120., 140., 160., 180., 200.,
       220., 240., 260., 280., 300., 320., 340., 360., 380., 400., 420.,
       440., 460., 480., 500., 520., 540., 560., 580., 600., 620.])

In [152]:
runner2=(a*20)+40

In [153]:
runner2

array([ 40.,  50.,  60.,  70.,  80.,  90., 100., 110., 120., 130., 140.,
       150., 160., 170., 180., 190., 200., 210., 220., 230., 240., 250.,
       260., 270., 280., 290., 300., 310., 320., 330., 340., 350.])

Let's subtract the <b>runner2</b> array from the <b>runner1</b> array.

In [154]:
x=runner2-runner1

In [155]:
x

array([  40.,   30.,   20.,   10.,    0.,  -10.,  -20.,  -30.,  -40.,
        -50.,  -60.,  -70.,  -80.,  -90., -100., -110., -120., -130.,
       -140., -150., -160., -170., -180., -190., -200., -210., -220.,
       -230., -240., -250., -260., -270.])

Let' construct a Berkeley table with these three arrays

In [156]:
from datascience import Table

In [160]:
runner_table=Table().with_columns(['Time',time,'Runner #1',runner1,'Runner #2',runner2])

In [161]:
runner_table

Time | Runner #1 | Runner #2
0    | 0         | 40
0.5  | 20        | 50
1    | 40        | 60
1.5  | 60        | 70
2    | 80        | 80
2.5  | 100       | 90
3    | 120       | 100
3.5  | 140       | 110
4    | 160       | 120
4.5  | 180       | 130
... (22 rows omitted)

In [122]:
a = np.arange(1,16,0.5)

In [123]:
t=Table().with_columns(['a',a,'bruce',bruce,'bolt',bolt])

In [108]:
t

a    | bruce | bolt
0    | 40    | 0
1    | 50    | 40
2    | 60    | 80
3    | 70    | 120
4    | 80    | 160
5    | 90    | 200
6    | 100   | 240
7    | 110   | 280
8    | 120   | 320
9    | 130   | 360
... (20 rows omitted)