http://data8.org/datascience/predicates.html?highlight=predicate

<b>Comparing the Berkeley datascience where method/predicte to Numpy Slices</b>

In [2]:
from datascience import Table
import numpy as np
demo=Table.read_table('heartrate.csv')

In [3]:
demo

timestamp                 | heartrate
2020-10-01 20:42:22 -0400 | 99
2020-10-01 20:47:46 -0400 | 67
2020-10-01 20:50:14 -0400 | 107
2020-10-01 20:50:19 -0400 | 107
2020-10-01 20:57:39 -0400 | 63
2020-10-01 21:02:07 -0400 | 57
2020-10-01 21:05:08 -0400 | 67
2020-10-01 21:11:29 -0400 | 77
2020-10-01 21:16:27 -0400 | 70
2020-10-01 21:20:14 -0400 | 74
... (12165 rows omitted)

In [4]:
hr=demo[1]

In [16]:
hr[hr<48]

array([47., 44., 47., 46., 45.])

In [6]:
len(hr[hr<50])

14

Let's see how to extract this same data with the Berkeley datascience module where predicate.

http://data8.org/datascience/predicates.html?highlight=predicate

In [20]:
from datascience.predicates import are

In [21]:
demo.columns #A Berkeley datascience method to list arrays inside of the Table.

(array(['2020-10-01 20:42:22 -0400', '2020-10-01 20:47:46 -0400',
        '2020-10-01 20:50:14 -0400', ..., '2021-03-18 02:39:51 -0400',
        '2021-03-18 02:44:16 -0400', '2021-03-18 02:50:46 -0400'],
       dtype='<U25'),
 array([ 99.,  67., 107., ...,  61.,  62.,  65.]))

In [22]:
demo.labels

('timestamp', 'heartrate')

In [15]:
#t.where('Waists', are.below(38)) Here is an example from the documentation.
demo.where('heartrate', are.below(48))

timestamp                 | heartrate
2020-11-22 04:45:32 -0400 | 47
2020-11-22 05:10:26 -0400 | 44
2020-11-22 05:43:58 -0400 | 47
2021-01-21 02:51:31 -0400 | 46
2021-02-09 23:36:25 -0400 | 45

In [17]:
hr[hr<48] #Compare this numpy slicing operation to the datascience where output.
# The extracted heartrate data between the two methods is identical. 

array([47., 44., 47., 46., 45.])

TypeError: 'tuple' object is not callable